### ISSUE TITLE
Downloads Wrong Instagram Story Picture

### ISSUE THREAD

**Issue by GreasyTamperMonkey** [y252328/Instagram_Download_Button#1]
On January 27th, Instagram changed how they displayed stories. The button still downloads videos correctly. If you click on any image other than the first one in the series, the button downloads the first image in the series but with the name of the clicked image.

**Comment by rudsonalonso** [comment]
Same here

**Comment by y252328** [comment]
Thanks for your feedback. I'll check this problem this weekend.

**Comment by y252328** [comment]
Hi, 
I have updated the script to fix this problem.

**Comment by rudsonalonso** [comment]
Working again, Thank you
