### ISSUE TITLE
Extra period/dot . at the end of filenames

### ISSUE THREAD

**Issue by Photodeus** [y252328/Instagram_Download_Button#10]
When I download any content, posts, stories etc. from Instagram on Chrome filenames are ending in a dot before the file extension, thus every file has two dots in their filenames.

Filenames look like this (cropped for anonymity)

--950610_n..jpg
--transcode_output_dashinit..mp4
--7468409_n..mp4

Just happening for me or is this a bug in the script?

Chrome version 96.0.4664.110
Script version 1.9.5

**Comment by Photodeus** [comment]
Bug seems to stem from this line:

https://github.com/y252328/Instagram_Download_Button/blob/09181e1b5965359768a2e3ae0f9ff4dc9a78f04c/instagram-dl.user.js#L254

mediaName ends up with a trailing period (.)

**Comment by y252328** [comment]
You are right and fixed in v1.9.6.
Thanks.
