### ISSUE TITLE
Buggy behaviour with posts of multiple images/videos

### ISSUE THREAD

**Issue by gvdvg** [y252328/Instagram_Download_Button#13]
Say there are 6 images in a post, moving through and clicking the button on each image gets images 1, 2, 3, 3, 5, where clicking on the 4th gets you the 3rd again and clicking on the 6th gives you nothing, or maybe another unpredictable combination of images
I hope this made sense

using Firefox 97.0.1

thanks

**Comment by y252328** [comment]
I don't encounter this issue recently. Could you provide the post link?

**Comment by skirtor** [comment]
in line 298
             // multiple imgs or videos
             let idx = 0;
             // check current index
-            if (!articleNode.querySelector('.coreSpriteLeftChevron')) {
+            if (!articleNode.querySelector('button[aria-label="Go Back"]')) {
                 idx = 0;
-            } else if (!articleNode.querySelector('.coreSpriteRightChevron')) {
+            } else if (!articleNode.querySelector('button[aria-label="Next"]')) {
                 idx = list.length - 1;
             } else idx = 1;
 
             let node = list[idx];

**Comment by talizea** [comment]
> I don't encounter this issue recently. Could you provide the post link?

Example: https://www.instagram.com/p/CdDkUbZsQQA/

Skips a few images and downloads another one twice.

**Comment by FlowerForWar** [comment]
> > I don't encounter this issue recently. Could you provide the post link?
> 
> Example: https://www.instagram.com/p/CdDkUbZsQQA/
> 
> Skips a few images and downloads another one twice.

Was having the same issue myself, specially on my Android phone. Try [this test fork](https://github.com/FlowerForWar/Instagram_Download_Button/raw/master/instagram-dl.user.js), and see if it fixes your issue as well. Then [y252328](https://github.com/y252328) can modify the code.

**Comment by talizea** [comment]
> > > I don't encounter this issue recently. Could you provide the post link?
> > 
> > 
> > Example: [instagram.com/p/CdDkUbZsQQA](https://www.instagram.com/p/CdDkUbZsQQA/)
> > Skips a few images and downloads another one twice.
> 
> Was having the same issue myself, specially on my Android phone. Try [this test fork](https://github.com/FlowerForWar/Instagram_Download_Button/raw/master/instagram-dl.user.js), and see if it fixes your issue as well. Then [y252328](https://github.com/y252328) can modify the code.

Got 10 different images with your fork, no duplicates, whoo! The file name format appears to be slightly different, but that's no issue for me at least.

**Comment by FlowerForWar** [comment]
> The file name format appears to be slightly different
```js
const postFilenameTemplate = '%postId%-%mediaIndex%-%id%';
```
That is some change I made along with other, as I like it this way, kind of how I'm used to it actually.

[y252328](https://github.com/y252328) should feel free to modify the original code, using my fork, as they see fit.

**Comment by y252328** [comment]
Hi [FlowerForWar](https://github.com/FlowerForWar),

Thanks for your great fork!
I have merged your code into master branch (commit [192c6a](https://github.com/y252328/Instagram_Download_Button/commit/192c6ab340fa532fd0c3ab717419f82d1a7b6bc0)) and applied some modifications (please refer to commit message).
Please take a look and feel free to reply to this issue or file a new issue if you have any concern, thanks.

**Comment by FlowerForWar** [comment]
> 

No problem. Thank you for this great user script as well.
I'm new to Github and how things work here, if I have an issue I'll let you know.
