### ISSUE TITLE
Correct typo 

### ISSUE THREAD

**Issue by GIPeon** [y252328/Instagram_Download_Button#14]
Hi small correction, `storySeletor ` should be `storySelector ` (there is a missing **c** in Seletor). Just because maybe later on a new piece is added and pointing at `storySelector` would error out. Not an issue right now because all references are same. Thank you for your script 🥇 

https://github.com/y252328/Instagram_Download_Button/blob/dc8c58d2ce864d9f77398ffef1bbf54758f8a843/instagram-dl.user.js#L115

https://github.com/y252328/Instagram_Download_Button/blob/dc8c58d2ce864d9f77398ffef1bbf54758f8a843/instagram-dl.user.js#L136-L137

**Comment by y252328** [comment]
Thanks for catching this. I will correct this.
