### ISSUE TITLE
I want use your  code in my project

### ISSUE THREAD

**Issue by PureBrowser** [y252328/Instagram_Download_Button#24]
your js code works great, I want use your code in my project， Do I need to pay for you code?

**Comment by FlowerForWar** [comment]
I'm not the author but I'm curious to know what kind of use. 

Are you going to copy past the whole user script? or just use few functions and techniques, that this user script has?

**Comment by y252328** [comment]
You can use this script (instagram-dl.user.js) without any charge just noting the source (i.e., this repository).  
But welcome to [buy me a coffee](https://www.buymeacoffee.com/y252328).

**Comment by PureBrowser** [comment]
> You can use this script (instagram-dl.user.js) without any charge just noting the source (i.e., this repository). But welcome to [buy me a coffee](https://www.buymeacoffee.com/y252328).

thanks

**Comment by PureBrowser** [comment]
> I'm not the author but I'm curious to know what kind of use.
> 
> Are you going to copy past the whole user script? or just use few functions and techniques, that this user script has?

i hava a android browser in google play, i want use it download videos
