### ISSUE TITLE
Some video's don't have a download link.

### ISSUE THREAD

**Issue by MickeyM007** [y252328/Instagram_Download_Button#25]
Hello!
Instagram (Facebook) is busy with updates and work on the site, as we all know..
**Some videos do not have a download link. Is that just for me?**

eg: https://www.instagram.com/p/Cly6Gimqt6-/
_(For some reason I can't 'direct link' an Instagram post in Firefox, that's new too! Copying the url above and putting it in a tab gives me a blank screen. I can link profiles directly, but it doesn't work with posted videos and photos links. Only with FF. ) _

Edit: Is it possible to change the date format to: **dd-mm-yyyy** without the time?

Thanks!!

**Comment by y252328** [comment]
Hi Mickey,
I have tested your link, but it works well in my environment (Windows, Chrome).
Could you help test in Chrome?

About the date format, unfortunately it cannot be quickly changed now. But I will add this to the to-do list.

**Comment by y252328** [comment]
Hi,
I have added datatime formating feature from 1.16.
You can change line 57 `datetimeTemplate` to what you want.
For example, `%d%-%m%-%y%` for dd-mm-yyyy.
