### ISSUE TITLE
Seems to have stopped working on the main feed

### ISSUE THREAD

**Issue by thinkpad4** [y252328/Instagram_Download_Button#27]
When viewing the main feed, clicking the button doesn't do anything on pics or vids.

**Comment by ZorisBube** [comment]
Yes, same for me...

-----------------------
Windows 10
Firefox 109.0
Tampermonkey
-----------------------

**Comment by y252328** [comment]
I have uploaded the new script on [greasyfork](https://greasyfork.org/zh-TW/scripts/406535-instagram-download-button). Please update and try again.

**Comment by ZorisBube** [comment]
> I have uploaded the new script on [greasyfork](https://greasyfork.org/zh-TW/scripts/406535-instagram-download-button). Please update and try again.

Yes, it is working now as supposed to be. Thank you y252328!
