### ISSUE TITLE
Stopped work 

### ISSUE THREAD

**Issue by rudsonalonso** [y252328/Instagram_Download_Button#3]
Just stopped work on Microsoft Edge (Chromium), download and open new tab icon just gone, just for me or script issue? 
![msedge_11-02-2021_00-54-30__Instagram_e_mais_6_páginas_-_Pessoal_-_Microsoft​___633x73](https://user-images.githubusercontent.com/9455667/107603629-bc9c6580-6c03-11eb-9842-d839ce47fac1.png)

**Comment by y252328** [comment]
This was the script issue due to Instagram modified the website.
Now, I have fixed it.
