### ISSUE TITLE
Wrong button position in new tab

### ISSUE THREAD

**Issue by sn3akyb3ar** [y252328/Instagram_Download_Button#30]
I noticed that the download button position has changed when you open posts in new tabs (from push notifications for example), and it's hard to click it if you're following the account (or even impossible if it has a long username).

![image](https://user-images.githubusercontent.com/34551334/225791014-733f9f57-def1-4c77-a0e6-34ed7f0348b8.png)

**Comment by y252328** [comment]
I cannot reproduce your issue on my compouter.
Can you provide more information (O.S., browser, script version...)?
Maybe you can try other browser or update the script.
![螢幕擷取畫面 2023-03-18 201059](https://user-images.githubusercontent.com/24591692/226105593-6f95d177-b6dd-4f10-8e16-57eeefbdb5e3.png)

**Comment by sn3akyb3ar** [comment]
Latest github version of the script, Firefox 111 x64 on Win7, Violentmonkey 2.14. But I just tried with Tampermonkey and fresh FF profile with the same result :(

**Comment by desdesifre** [comment]
i am having the same problem. win10 64 bit. firefox 111. greasemonkey 4.11 idb 1.16.0

**Comment by sn3akyb3ar** [comment]
> other browser

Just checked using freshly installed Brave 1.47.186 (last one that works on win 7) and Tampermonkey - same issue.

**Comment by y252328** [comment]
I still cannot reproduce this issue. There will not be an update until I can reproduce it.

**Comment by sn3akyb3ar** [comment]
@desdesifre, I just noticed that it's working as intended now, so if it's working for you too, I'm closing the issue.

**Comment by desdesifre** [comment]
@sn3akyb3ar yes it works, thanks
