### ISSUE TITLE
New issue with file type format

### ISSUE THREAD

**Issue by rudsonalonso** [y252328/Instagram_Download_Button#4]
Hey man, i need change the line 37 to .ext from the end template

old:     `const postFilenameTemplate = "%id%-%datetime%-%medianame%.%ext%-%datetime%";`
new one:      `const postFilenameTemplate = "%id%-%datetime%-%medianame%-%datetime%.%ext%";`

**Comment by y252328** [comment]
I committed the wrong script. The newest commit has changed the naming template back.
You can pull the new commit if you need.

**Comment by rudsonalonso** [comment]
Alright, thank you, good job
