### ISSUE TITLE
Not showing buttons on single video view.

### ISSUE THREAD

**Issue by marijuanatech** [y252328/Instagram_Download_Button#5]
When viewing a single video, it's not currently showing the download buttons. 

Example:
https://www.instagram.com/p/CLzolZ-jz0R/
https://imgur.com/a/DVaNZaI

Note: You have to click a picture, then refresh the page. Or follow a link to the image.

**Comment by marijuanatech** [comment]
Using version 1.9.2

Thanks for your great script. One less thing I have to manage.

**Comment by y252328** [comment]
Thank you for your feedback.
I have fixed this issue, please check.

**Comment by marijuanatech** [comment]
Thank you very much - issue is fixed!  I'd like to contribute financially in some way when I'm able to. This script is very helpful - thanks again.

**Comment by y252328** [comment]
😀
